name: Linting job

on:
  push:
  pull_request:
    branches: 
      - main

defaults:
  run:
    working-directory: src

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Linter
        run: |
          npm ci
          npm run lint