
# File: .github/workflows/workflow.yml

on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4E4C269EF68740628024D8A93FAE50E2 }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
